sudo: required
language: go
services:
  - docker
go:
  - 1.10.3
script:
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - make test
after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io;
      make push;
    fi
